// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2gw0nibvDvkoLcQSgGXHnM5KYw7UsgYc',
    appId: '1:776500448600:web:c5cf55aabe65ad975ea92d',
    messagingSenderId: '776500448600',
    projectId: 'eurotech-docs-77f50',
    authDomain: 'eurotech-docs-77f50.firebaseapp.com',
    databaseURL: 'https://eurotech-docs-77f50-default-rtdb.firebaseio.com',
    storageBucket: 'eurotech-docs-77f50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW-iLVn8ueyMMHGhublcgo6s9zyppqVl8',
    appId: '1:776500448600:android:4105f93a4f0346f25ea92d',
    messagingSenderId: '776500448600',
    projectId: 'eurotech-docs-77f50',
    databaseURL: 'https://eurotech-docs-77f50-default-rtdb.firebaseio.com',
    storageBucket: 'eurotech-docs-77f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8aSUDazxO6TuJrnoUoz8DUnxWWNkTp-I',
    appId: '1:776500448600:ios:1613df4ec6aa281b5ea92d',
    messagingSenderId: '776500448600',
    projectId: 'eurotech-docs-77f50',
    databaseURL: 'https://eurotech-docs-77f50-default-rtdb.firebaseio.com',
    storageBucket: 'eurotech-docs-77f50.appspot.com',
    iosClientId: '776500448600-kchcr035tdsi30g946dnl3p5eequc7v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.euroDocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8aSUDazxO6TuJrnoUoz8DUnxWWNkTp-I',
    appId: '1:776500448600:ios:5bb52fb7d18f297b5ea92d',
    messagingSenderId: '776500448600',
    projectId: 'eurotech-docs-77f50',
    databaseURL: 'https://eurotech-docs-77f50-default-rtdb.firebaseio.com',
    storageBucket: 'eurotech-docs-77f50.appspot.com',
    iosClientId: '776500448600-gmfkqv698iil6b6d43em988dorlogep4.apps.googleusercontent.com',
    iosBundleId: 'com.example.euroDocs.RunnerTests',
  );
}
